// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: skipbo.proto

package skipbopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional seed for deterministic games (0 = random).
	Seed uint64 `protobuf:"varint,1,opt,name=seed,proto3" json:"seed,omitempty"`
	// Number of opponents (default 1 if not set).
	NumOpponents int32 `protobuf:"varint,2,opt,name=num_opponents,json=numOpponents,proto3" json:"num_opponents,omitempty"`
	// Stock pile size (default 30 if not set).
	StockSize     int32 `protobuf:"varint,3,opt,name=stock_size,json=stockSize,proto3" json:"stock_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_skipbo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skipbo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_skipbo_proto_rawDescGZIP(), []int{0}
}

func (x *ResetRequest) GetSeed() uint64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *ResetRequest) GetNumOpponents() int32 {
	if x != nil {
		return x.NumOpponents
	}
	return 0
}

func (x *ResetRequest) GetStockSize() int32 {
	if x != nil {
		return x.StockSize
	}
	return 0
}

type StepRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Discrete action index (0–59).
	Action        int32 `protobuf:"varint,1,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepRequest) Reset() {
	*x = StepRequest{}
	mi := &file_skipbo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepRequest) ProtoMessage() {}

func (x *StepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skipbo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepRequest.ProtoReflect.Descriptor instead.
func (*StepRequest) Descriptor() ([]byte, []int) {
	return file_skipbo_proto_rawDescGZIP(), []int{1}
}

func (x *StepRequest) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

type Observation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Flat state vector (length 54).
	State []float64 `protobuf:"fixed64,1,rep,packed,name=state,proto3" json:"state,omitempty"`
	// Legal action mask (length 60). True = action is legal.
	ActionMask    []bool `protobuf:"varint,2,rep,packed,name=action_mask,json=actionMask,proto3" json:"action_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observation) Reset() {
	*x = Observation{}
	mi := &file_skipbo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observation) ProtoMessage() {}

func (x *Observation) ProtoReflect() protoreflect.Message {
	mi := &file_skipbo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observation.ProtoReflect.Descriptor instead.
func (*Observation) Descriptor() ([]byte, []int) {
	return file_skipbo_proto_rawDescGZIP(), []int{2}
}

func (x *Observation) GetState() []float64 {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *Observation) GetActionMask() []bool {
	if x != nil {
		return x.ActionMask
	}
	return nil
}

type StepResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Observation after the action.
	Obs *Observation `protobuf:"bytes,1,opt,name=obs,proto3" json:"obs,omitempty"`
	// Shaped reward for this step.
	Reward float64 `protobuf:"fixed64,2,opt,name=reward,proto3" json:"reward,omitempty"`
	// Whether the game is over.
	Done bool `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	// Index of the winner (-1 if game not over).
	Winner int32 `protobuf:"varint,4,opt,name=winner,proto3" json:"winner,omitempty"`
	// Additional info for logging.
	Info          *StepInfo `protobuf:"bytes,5,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepResult) Reset() {
	*x = StepResult{}
	mi := &file_skipbo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResult) ProtoMessage() {}

func (x *StepResult) ProtoReflect() protoreflect.Message {
	mi := &file_skipbo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResult.ProtoReflect.Descriptor instead.
func (*StepResult) Descriptor() ([]byte, []int) {
	return file_skipbo_proto_rawDescGZIP(), []int{3}
}

func (x *StepResult) GetObs() *Observation {
	if x != nil {
		return x.Obs
	}
	return nil
}

func (x *StepResult) GetReward() float64 {
	if x != nil {
		return x.Reward
	}
	return 0
}

func (x *StepResult) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *StepResult) GetWinner() int32 {
	if x != nil {
		return x.Winner
	}
	return 0
}

func (x *StepResult) GetInfo() *StepInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type StepInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TurnNumber          int32                  `protobuf:"varint,1,opt,name=turn_number,json=turnNumber,proto3" json:"turn_number,omitempty"`
	AgentStockRemaining int32                  `protobuf:"varint,2,opt,name=agent_stock_remaining,json=agentStockRemaining,proto3" json:"agent_stock_remaining,omitempty"`
	PlayedFromStock     bool                   `protobuf:"varint,3,opt,name=played_from_stock,json=playedFromStock,proto3" json:"played_from_stock,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StepInfo) Reset() {
	*x = StepInfo{}
	mi := &file_skipbo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepInfo) ProtoMessage() {}

func (x *StepInfo) ProtoReflect() protoreflect.Message {
	mi := &file_skipbo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepInfo.ProtoReflect.Descriptor instead.
func (*StepInfo) Descriptor() ([]byte, []int) {
	return file_skipbo_proto_rawDescGZIP(), []int{4}
}

func (x *StepInfo) GetTurnNumber() int32 {
	if x != nil {
		return x.TurnNumber
	}
	return 0
}

func (x *StepInfo) GetAgentStockRemaining() int32 {
	if x != nil {
		return x.AgentStockRemaining
	}
	return 0
}

func (x *StepInfo) GetPlayedFromStock() bool {
	if x != nil {
		return x.PlayedFromStock
	}
	return false
}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_skipbo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skipbo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_skipbo_proto_rawDescGZIP(), []int{5}
}

type MetricsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalGames        int64                  `protobuf:"varint,1,opt,name=total_games,json=totalGames,proto3" json:"total_games,omitempty"`
	TotalSteps        int64                  `protobuf:"varint,2,opt,name=total_steps,json=totalSteps,proto3" json:"total_steps,omitempty"`
	AgentWins         int64                  `protobuf:"varint,3,opt,name=agent_wins,json=agentWins,proto3" json:"agent_wins,omitempty"`
	AvgGameLength     float64                `protobuf:"fixed64,4,opt,name=avg_game_length,json=avgGameLength,proto3" json:"avg_game_length,omitempty"`
	AvgStockpilePlays float64                `protobuf:"fixed64,5,opt,name=avg_stockpile_plays,json=avgStockpilePlays,proto3" json:"avg_stockpile_plays,omitempty"`
	IllegalActions    int64                  `protobuf:"varint,6,opt,name=illegal_actions,json=illegalActions,proto3" json:"illegal_actions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_skipbo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skipbo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_skipbo_proto_rawDescGZIP(), []int{6}
}

func (x *MetricsResponse) GetTotalGames() int64 {
	if x != nil {
		return x.TotalGames
	}
	return 0
}

func (x *MetricsResponse) GetTotalSteps() int64 {
	if x != nil {
		return x.TotalSteps
	}
	return 0
}

func (x *MetricsResponse) GetAgentWins() int64 {
	if x != nil {
		return x.AgentWins
	}
	return 0
}

func (x *MetricsResponse) GetAvgGameLength() float64 {
	if x != nil {
		return x.AvgGameLength
	}
	return 0
}

func (x *MetricsResponse) GetAvgStockpilePlays() float64 {
	if x != nil {
		return x.AvgStockpilePlays
	}
	return 0
}

func (x *MetricsResponse) GetIllegalActions() int64 {
	if x != nil {
		return x.IllegalActions
	}
	return 0
}

var File_skipbo_proto protoreflect.FileDescriptor

const file_skipbo_proto_rawDesc = "" +
	"\n" +
	"\fskipbo.proto\x12\x06skipbo\"f\n" +
	"\fResetRequest\x12\x12\n" +
	"\x04seed\x18\x01 \x01(\x04R\x04seed\x12#\n" +
	"\rnum_opponents\x18\x02 \x01(\x05R\fnumOpponents\x12\x1d\n" +
	"\n" +
	"stock_size\x18\x03 \x01(\x05R\tstockSize\"%\n" +
	"\vStepRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\x05R\x06action\"D\n" +
	"\vObservation\x12\x14\n" +
	"\x05state\x18\x01 \x03(\x01R\x05state\x12\x1f\n" +
	"\vaction_mask\x18\x02 \x03(\bR\n" +
	"actionMask\"\x9d\x01\n" +
	"\n" +
	"StepResult\x12%\n" +
	"\x03obs\x18\x01 \x01(\v2\x13.skipbo.ObservationR\x03obs\x12\x16\n" +
	"\x06reward\x18\x02 \x01(\x01R\x06reward\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\x12\x16\n" +
	"\x06winner\x18\x04 \x01(\x05R\x06winner\x12$\n" +
	"\x04info\x18\x05 \x01(\v2\x10.skipbo.StepInfoR\x04info\"\x8b\x01\n" +
	"\bStepInfo\x12\x1f\n" +
	"\vturn_number\x18\x01 \x01(\x05R\n" +
	"turnNumber\x122\n" +
	"\x15agent_stock_remaining\x18\x02 \x01(\x05R\x13agentStockRemaining\x12*\n" +
	"\x11played_from_stock\x18\x03 \x01(\bR\x0fplayedFromStock\"\x10\n" +
	"\x0eMetricsRequest\"\xf3\x01\n" +
	"\x0fMetricsResponse\x12\x1f\n" +
	"\vtotal_games\x18\x01 \x01(\x03R\n" +
	"totalGames\x12\x1f\n" +
	"\vtotal_steps\x18\x02 \x01(\x03R\n" +
	"totalSteps\x12\x1d\n" +
	"\n" +
	"agent_wins\x18\x03 \x01(\x03R\tagentWins\x12&\n" +
	"\x0favg_game_length\x18\x04 \x01(\x01R\ravgGameLength\x12.\n" +
	"\x13avg_stockpile_plays\x18\x05 \x01(\x01R\x11avgStockpilePlays\x12'\n" +
	"\x0fillegal_actions\x18\x06 \x01(\x03R\x0eillegalActions2\xaf\x01\n" +
	"\tSkipBoEnv\x122\n" +
	"\x05Reset\x12\x14.skipbo.ResetRequest\x1a\x13.skipbo.Observation\x12/\n" +
	"\x04Step\x12\x13.skipbo.StepRequest\x1a\x12.skipbo.StepResult\x12=\n" +
	"\n" +
	"GetMetrics\x12\x16.skipbo.MetricsRequest\x1a\x17.skipbo.MetricsResponseB0Z.github.com/RyanMcCrary22/skipbo/proto/skipbopbb\x06proto3"

var (
	file_skipbo_proto_rawDescOnce sync.Once
	file_skipbo_proto_rawDescData []byte
)

func file_skipbo_proto_rawDescGZIP() []byte {
	file_skipbo_proto_rawDescOnce.Do(func() {
		file_skipbo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skipbo_proto_rawDesc), len(file_skipbo_proto_rawDesc)))
	})
	return file_skipbo_proto_rawDescData
}

var file_skipbo_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_skipbo_proto_goTypes = []any{
	(*ResetRequest)(nil),    // 0: skipbo.ResetRequest
	(*StepRequest)(nil),     // 1: skipbo.StepRequest
	(*Observation)(nil),     // 2: skipbo.Observation
	(*StepResult)(nil),      // 3: skipbo.StepResult
	(*StepInfo)(nil),        // 4: skipbo.StepInfo
	(*MetricsRequest)(nil),  // 5: skipbo.MetricsRequest
	(*MetricsResponse)(nil), // 6: skipbo.MetricsResponse
}
var file_skipbo_proto_depIdxs = []int32{
	2, // 0: skipbo.StepResult.obs:type_name -> skipbo.Observation
	4, // 1: skipbo.StepResult.info:type_name -> skipbo.StepInfo
	0, // 2: skipbo.SkipBoEnv.Reset:input_type -> skipbo.ResetRequest
	1, // 3: skipbo.SkipBoEnv.Step:input_type -> skipbo.StepRequest
	5, // 4: skipbo.SkipBoEnv.GetMetrics:input_type -> skipbo.MetricsRequest
	2, // 5: skipbo.SkipBoEnv.Reset:output_type -> skipbo.Observation
	3, // 6: skipbo.SkipBoEnv.Step:output_type -> skipbo.StepResult
	6, // 7: skipbo.SkipBoEnv.GetMetrics:output_type -> skipbo.MetricsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_skipbo_proto_init() }
func file_skipbo_proto_init() {
	if File_skipbo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skipbo_proto_rawDesc), len(file_skipbo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_skipbo_proto_goTypes,
		DependencyIndexes: file_skipbo_proto_depIdxs,
		MessageInfos:      file_skipbo_proto_msgTypes,
	}.Build()
	File_skipbo_proto = out.File
	file_skipbo_proto_goTypes = nil
	file_skipbo_proto_depIdxs = nil
}
