// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: skipbo.proto

package skipbopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SkipBoEnv_Reset_FullMethodName      = "/skipbo.SkipBoEnv/Reset"
	SkipBoEnv_Step_FullMethodName       = "/skipbo.SkipBoEnv/Step"
	SkipBoEnv_GetMetrics_FullMethodName = "/skipbo.SkipBoEnv/GetMetrics"
)

// SkipBoEnvClient is the client API for SkipBoEnv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SkipBoEnv exposes a Gym-style Step/Reset API for training RL agents.
type SkipBoEnvClient interface {
	// Reset starts a new game and returns the initial observation.
	Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error)
	// Step executes one agent action and returns the resulting observation,
	// reward, and done flag. Between agent turns, opponents play automatically.
	Step(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (*StepResult, error)
	// GetMetrics returns cumulative training metrics from the server.
	GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error)
}

type skipBoEnvClient struct {
	cc grpc.ClientConnInterface
}

func NewSkipBoEnvClient(cc grpc.ClientConnInterface) SkipBoEnvClient {
	return &skipBoEnvClient{cc}
}

func (c *skipBoEnvClient) Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetResponse)
	err := c.cc.Invoke(ctx, SkipBoEnv_Reset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skipBoEnvClient) Step(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (*StepResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StepResult)
	err := c.cc.Invoke(ctx, SkipBoEnv_Step_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skipBoEnvClient) GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricsResponse)
	err := c.cc.Invoke(ctx, SkipBoEnv_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkipBoEnvServer is the server API for SkipBoEnv service.
// All implementations must embed UnimplementedSkipBoEnvServer
// for forward compatibility.
//
// SkipBoEnv exposes a Gym-style Step/Reset API for training RL agents.
type SkipBoEnvServer interface {
	// Reset starts a new game and returns the initial observation.
	Reset(context.Context, *ResetRequest) (*ResetResponse, error)
	// Step executes one agent action and returns the resulting observation,
	// reward, and done flag. Between agent turns, opponents play automatically.
	Step(context.Context, *StepRequest) (*StepResult, error)
	// GetMetrics returns cumulative training metrics from the server.
	GetMetrics(context.Context, *MetricsRequest) (*MetricsResponse, error)
	mustEmbedUnimplementedSkipBoEnvServer()
}

// UnimplementedSkipBoEnvServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSkipBoEnvServer struct{}

func (UnimplementedSkipBoEnvServer) Reset(context.Context, *ResetRequest) (*ResetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedSkipBoEnvServer) Step(context.Context, *StepRequest) (*StepResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Step not implemented")
}
func (UnimplementedSkipBoEnvServer) GetMetrics(context.Context, *MetricsRequest) (*MetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedSkipBoEnvServer) mustEmbedUnimplementedSkipBoEnvServer() {}
func (UnimplementedSkipBoEnvServer) testEmbeddedByValue()                   {}

// UnsafeSkipBoEnvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkipBoEnvServer will
// result in compilation errors.
type UnsafeSkipBoEnvServer interface {
	mustEmbedUnimplementedSkipBoEnvServer()
}

func RegisterSkipBoEnvServer(s grpc.ServiceRegistrar, srv SkipBoEnvServer) {
	// If the following call panics, it indicates UnimplementedSkipBoEnvServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SkipBoEnv_ServiceDesc, srv)
}

func _SkipBoEnv_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkipBoEnvServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkipBoEnv_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkipBoEnvServer).Reset(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkipBoEnv_Step_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkipBoEnvServer).Step(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkipBoEnv_Step_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkipBoEnvServer).Step(ctx, req.(*StepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkipBoEnv_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkipBoEnvServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkipBoEnv_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkipBoEnvServer).GetMetrics(ctx, req.(*MetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SkipBoEnv_ServiceDesc is the grpc.ServiceDesc for SkipBoEnv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SkipBoEnv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "skipbo.SkipBoEnv",
	HandlerType: (*SkipBoEnvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reset",
			Handler:    _SkipBoEnv_Reset_Handler,
		},
		{
			MethodName: "Step",
			Handler:    _SkipBoEnv_Step_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _SkipBoEnv_GetMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "skipbo.proto",
}
