# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import skipbo_pb2 as skipbo__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in skipbo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SkipBoEnvStub(object):
    """SkipBoEnv exposes a Gym-style Step/Reset API for training RL agents.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Reset = channel.unary_unary(
                '/skipbo.SkipBoEnv/Reset',
                request_serializer=skipbo__pb2.ResetRequest.SerializeToString,
                response_deserializer=skipbo__pb2.Observation.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/skipbo.SkipBoEnv/Step',
                request_serializer=skipbo__pb2.StepRequest.SerializeToString,
                response_deserializer=skipbo__pb2.StepResult.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/skipbo.SkipBoEnv/GetMetrics',
                request_serializer=skipbo__pb2.MetricsRequest.SerializeToString,
                response_deserializer=skipbo__pb2.MetricsResponse.FromString,
                _registered_method=True)


class SkipBoEnvServicer(object):
    """SkipBoEnv exposes a Gym-style Step/Reset API for training RL agents.
    """

    def Reset(self, request, context):
        """Reset starts a new game and returns the initial observation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Step executes one agent action and returns the resulting observation,
        reward, and done flag. Between agent turns, opponents play automatically.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """GetMetrics returns cumulative training metrics from the server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SkipBoEnvServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=skipbo__pb2.ResetRequest.FromString,
                    response_serializer=skipbo__pb2.Observation.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=skipbo__pb2.StepRequest.FromString,
                    response_serializer=skipbo__pb2.StepResult.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=skipbo__pb2.MetricsRequest.FromString,
                    response_serializer=skipbo__pb2.MetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'skipbo.SkipBoEnv', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('skipbo.SkipBoEnv', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SkipBoEnv(object):
    """SkipBoEnv exposes a Gym-style Step/Reset API for training RL agents.
    """

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/skipbo.SkipBoEnv/Reset',
            skipbo__pb2.ResetRequest.SerializeToString,
            skipbo__pb2.Observation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/skipbo.SkipBoEnv/Step',
            skipbo__pb2.StepRequest.SerializeToString,
            skipbo__pb2.StepResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/skipbo.SkipBoEnv/GetMetrics',
            skipbo__pb2.MetricsRequest.SerializeToString,
            skipbo__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
